name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2 Instance
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
            cd /var/www/html
            sudo git clone https://github.com/naja-cv/<your-repo>auto-deploy-webapp.git temp || true
            sudo cp -r temp/* .
            sudo rm -rf temp
            sudo systemctl restart apache2 || true
          EOF
